name: Frontend CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  secret-scan:
    name: Secret scan
    runs-on: ubuntu-latest

    permissions: 
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  test:
    name: Frontend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run tests
        run: npm test
  

  build-and-scan:
    name: Build and Scan Docker Image
    needs: 
      - test
      - secret-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t devops-employee-frontend:${{ github.sha }} \
            .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devops-employee-frontend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      
      - name: Save Docker image
        run: |
          docker save \
            devops-employee-frontend:${{ github.sha }} \
            -o devops-employee-frontend.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-employee-frontend-${{ github.sha }}
          path: devops-employee-frontend.tar
          retention-days: 1